// Data/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using HabitTrackerApi.Models; // Ensure this is using the correct namespace

namespace HabitTrackerApi.Data
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        public DbSet<User> Users { get; set; } = null!;
        public DbSet<Habit> Habits { get; set; } = null!; // Changed from Tasks
        public DbSet<Record> Records { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Record>()
                .HasOne(r => r.User)
                .WithMany(u => u.Records)
                .HasForeignKey(r => r.UserId);

            modelBuilder.Entity<Record>()
                .HasOne(r => r.Habit) // Changed from Task
                .WithMany(h => h.Records) // Changed from t => t.Records
                .HasForeignKey(r => r.HabitId); // Changed from TaskId

            // Ensure UUIDs are generated by the database for PostgreSQL
            modelBuilder.Entity<User>()
                .Property(u => u.Id)
                .HasDefaultValueSql("gen_random_uuid()");

            modelBuilder.Entity<Habit>() // Changed from Models.Task
                .Property(h => h.Id) // Changed from t => t.Id
                .HasDefaultValueSql("gen_random_uuid()");

            modelBuilder.Entity<Record>()
                .Property(r => r.Id)
                .HasDefaultValueSql("gen_random_uuid()");
        }
    }
}
